WEAS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home',include('home.urls')),
    path('',include('user.urls')),
]

api/api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/alert/', include('users.urls')),
    path('api/v1/', include('survey.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.authtoken')),
]

authentication/urls.py
from django.urls import path
from .views import *
app_name = 'auth'
urlpatterns = [
    path('user',user_list,name="user_index"),
    path('group',group_index,name="group_index"),
    path('permission',permission_index,name="permission_index"),
    path('user/register',register,name="user_create"),
    path('group/create',group_create,name="group_create"),
    path('user/edit/<id>/',user_update,name="user_update"),
    path('user/delete',user_delete,name="user_delete"),
    path('user/edit/<id>/password/',change_password,name="password_change"),
    path('group/edit/<id>/',group_update,name="group_update"),
]

weas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import login_page, register, logout_user, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('register/',register),
    path('login/',login_page,name='login'),
    path('logout/',logout_user,name='logout'),
    path('authentication/',include('authentication.urls',namespace='authentication')),
    path('risk-assesment/',include('risk_assesment.urls',namespace='risk_assesment')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _

class CustomUserManager(BaseUserManager):
    
    def create_user(self, email, password, **extra_fields):
       
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user


    def create_superuser(self, email, password, **extra_fields):
        
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):

    email = models.EmailField(("Email Address"), max_length=254,unique=True)
    image = models.ImageField(upload_to='profile/pictures', verbose_name='Profile Picture',blank=True)
   
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,  PasswordChangeForm
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User, Group, Permission
from crispy_forms.layout import Layout, Row, Column, Submit, Button, HTML, Hidden, Div
from crispy_forms.helper import FormHelper
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.utils.safestring import mark_safe
from authentication.models import CustomUser as User

class CreateUserForm(UserCreationForm):
    image = forms.ImageField( required=False)
    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'password1', 'password2','is_superuser','is_staff','is_active','image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
        'first_name', 'last_name','email','password1','password2',
        'is_superuser','is_staff','is_active','image',
        HTML('<button class="btn btn-success float-right" type="submit">Save</button><input type="hidden" name="slug" value=""></div></form>'),
    )

class UserUpdateForm(UserChangeForm):
    image = forms.ImageField( required=False)
    class Meta:
        model = User
        fields = ['first_name', 'last_name','email','user_permissions','groups',
                  'password','is_superuser','is_staff','is_active','image']
        help_text = {
            'password': None
        }
        widgets = {
            'user_permissions': FilteredSelectMultiple("Permission", False, attrs={'rows':'2'}),
            'groups': FilteredSelectMultiple("Group", False, attrs={'rows':'2'}),
        }
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
        'first_name', 'last_name', 'email','password',
        Row(
            Column('groups', css_class="form-group col-md-8 mb-0"),
        ),
        Row(
            Column('user_permissions', css_class="form-group col-md-8 mb-0"),
        ),
        'email','is_superuser','is_staff','is_active','image',
        HTML('<button class="btn btn-success float-right" type="submit">Save</button><input type="hidden" name="slug" value=""></div></form>'),
    )

class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'permissions': FilteredSelectMultiple("Permission", False, attrs={'rows':'2'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Column('name', css_class="form-group col-md-4 mb-0"),
            ),
                Row('permissions'),

            HTML('<button class="btn btn-success" type="submit">Save</button><input type="hidden" name="slug" value=""></div></form>'),
        )


class UserPasswordChangeForm(PasswordChangeForm):
    class Meta:
        field = '__all__'

authentication/templates/authentication/group/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from .models import UserProfile
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group, Permission
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username = username,password = password)
        if user is not None:
            login(request,user)
            return redirect('/')
        else:
            messages.info(request, 'Username or Password is incorrect')

    return render(request,'authentication/login.html')

def logoutuser(request):
    logout(request)
    return redirect('/login')

def register(request):
    user_form = CreateUserForm()
    profile_form = UserProfileForm()
    if request.method == 'POST':
        user_form = CreateUserForm(request.POST,request.FILES)
        # profile_form = UserProfileForm(request.POST,request.FILES)
        if user_form.is_valid():
            print(user_form.cleaned_data['image'])
            user = user_form.save()
            user_profile = UserProfile.objects.create(user=user,image=user_form.cleaned_data['image'])
            return redirect('/')
        print(user_form.cleaned_data)

    context = {
        'user_form':user_form,
        'title':'User'
    }
    return render(request,'authentication/register.html',context)

def user_update(request,id):
    user = User.objects.get(id=id)
    form = UserCreationForm(instance = user)
    if request.method == 'POST':
        user_form = CreateUserForm(request.POST,request.FILES)
     
    context = {
        'user_form':form,
        'title':'User'
    }
    return render(request,'authentication/register.html',context)  


def home(request):
    context = {
        'title':'Dashboard',
    }
    return render(request,'home/index.html',context=context)

def user_list(request):
    context = {
        'title':'User',
        'users': UserProfile.objects.all(),
    }
    print(User.objects.all())
    return render(request,'authentication/index.html',context=context)

def group_index(request):
    context = {
        'title':'Group',
        'groups': Group.objects.all(),
    }
    return render(request,'authentication/group/index.html',context=context)

def permission_index(request):
    context = {
        'title':'Permission',
        'group': Permission.objects.all(),
    }
    return render(request,'authentication/permission/index.html',context=context)

def group_create(request):
    context = {
        'title':'Group',
        'groups': Group.objects.all(),
    }
    return render(request,'authentication/group/index.html',context=context)

authentication/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, Permission
from .models import CustomUser as User

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username = username,password = password)
        if user is not None:
            login(request,user)
            return redirect('/')
        else:
            messages.info(request, 'Username or Password is incorrect')

    return render(request,'authentication/login.html')

def logout_user(request):
    logout(request)
    return redirect('/login')

def register(request):
    user_form = CreateUserForm()
    if request.method == 'POST':
        user_form = CreateUserForm(request.POST,request.FILES)
        if user_form.is_valid():
            user = user_form.save()
            return redirect('authentication:user_index')
    context = {
        'user_form':user_form,
        'title':'User'
    }
    return render(request,'authentication/register.html',context)

def change_password(request):
    form = UserPasswordChangeForm()
    context = {
        'user_form':form,
        'title':'Change Password'
    }
    return render(request,'authentication/register.html',context)

def user_update(request,id):
    user = User.objects.get(id=id)
    form = UserUpdateForm(instance = user)
    if request.method == 'POST':
        form = UserUpdateForm(request.POST,request.FILES,instance=user)
        if form.is_valid():
            form.save()
            return redirect('authentication:user_index')
    context = {
        'user_form':form,
        'title':'User'
    }
    return render(request,'authentication/register.html',context)  


def home(request):
    context = {
        'title':'Dashboard',
    }
    return render(request,'home/index.html',context=context)

def user_list(request):
    context = {
        'title':'User',
        'active_menu':'authentication',
        'users': User.objects.all(),
    }
    return render(request,'authentication/index.html',context=context)

def user_delete(request):
    id = request.POST.get('id')
    user = User.objects.get(id=id);
    print(user)

def group_index(request):
    context = {
        'title':'Group',
        'active_menu':'authentication',
        'groups': Group.objects.all(),
    }
    return render(request,'authentication/group/index.html',context=context)

def permission_index(request):
    context = {
        'title':'Permission',
        'group': Permission.objects.all(),
    }
    return render(request,'authentication/permission/index.html',context=context)

def group_create(request):
    form = GroupForm()
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authentication:group_index')
    context = {
        'title':'Group',
        'form': form,
    }
    return render(request,'authentication/group/create.html',context=context)

def group_update(request,id):
    group = Group.objects.get(id=id)
    form = GroupForm(instance=group)
    if request.method == 'POST':
        form = GroupForm(request.POST,instance=group)
    if form.is_valid():
        form.save()
        return redirect('authentication:group_index')
    context = {
        'title':'Group',
        'form': form,
    }
    return render(request,'authentication/group/create.html',context=context)

authentication/templates/authentication/index.html
{% extends 'base.html' %}{% load static from static %}{% block content%}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark"><i class="fas fa-user"></i>&nbsp;{{ title }}</h1>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">{{ title }}</li>
                </ol>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<div class="card card-danger card-outline">
    <div class="card-body">
        <div class="row">
            <a href="{% url 'authentication:user_create' %}" class="add-link">
                <p class="add-text"><i class="fa fa-plus">&nbsp;</i> Add {{ title }}</p>
            </a>
        </div>
        <div class="table-title">
            <p class="title-text">All {{ title }}s</p>
        </div>
        <table id="table" class="table table-bordered table-striped table-hover dataTable w-100">
            <thead>
                <tr>
                    <th>SN</th>
                    <th width="10">Photo</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Date Joined</th>
                    <th>Last Login</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td class="w-25">{% if user.image.url != '' %}
                        <img src="{{ user.image.url }}" class="w-25" alt="Photo"> {% endif %}</td>
                    <td>{{ user.first_name}} {{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>{{ user.date_joined }}</td>
                    <td>{{ user.last_login }}</td>
                    <td><a class="btn btn-success btn-xs btn-edit " href="{% url 'authentication:user_update' id=user.id %}"><span><i class="fas fa-edit "></i></span></a>
                        <form action="{% url 'authentication:user_delete' %}">
                            <input type="hidden" name="id" value="{{user.id}}">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-xs btn-delete" type="submit"><span><i class="far fa-trash-alt "></i></span></button></td>
                        </form>
                        
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

{% endblock %} {% block javascript %}
<script>
    $(function() {
        var table = $('#table').DataTable({
            'responsive': true,
            dom: 'Bfrtip',
            buttons: ['copy', 'csv', 'excel', 'pdf', 'print', 'colvis'],
        });
        table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container()));
        $(document).on('click', '.add-link', function() {
            $addForm.find('input').removeClass('is-invalid');
            $addForm.find('error').html('');
            $modal_form.modal();
        });
    });
</script>
{% endblock %}

authentication/templates/authentication/login.html
{% load static from static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>WEAS | Log in</title>

    <!-- Google Font: Source Sans Pro -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- icheck bootstrap -->
    <link
      rel="stylesheet"
      href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}" />
  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <a href="index2.html"><b>Admin</b>LTE</a>
      </div>
      <!-- /.login-logo -->
      <div class="card">
        <div class="card-body login-card-body">
          <p class="login-box-msg">Sign in to start your session</p>

          <form action="{% url 'login' %}" method="post">
            <div class="input-group mb-3">
              <input
                type="email"
                class="form-control"
                placeholder="Email"
                name="username"
                autocomplete="new-username"
                autocomplete="off"
                autocomplete="false"
                autocorrect="off"
              />
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-envelope"></span>
                </div>
              </div>
            </div>
            <div class="input-group mb-3">
              <input
                type="password"
                class="form-control"
                placeholder="Password"
                name="password"
                autocomplete="new-password"
                autocomplete="off"
                autocomplete="false"
                autocorrect="off"
              />
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-lock"></span>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-8">
                <div class="icheck-primary">
                  <input type="checkbox" id="remember" />
                  <label for="remember"> Remember Me </label>
                </div>
              </div>
            </div>
            <div class="row d-flex justify-content-center">
              <div class="col-4">
                <button type="submit" class="btn btn-primary btn-block">
                  Sign In
                </button>
              </div>
            </div>
            <div class="mt-2 d-flex justify-content-center">
              {% for message in messages %}
              <p class="error text-danger">{{ message }}</p>
              {% endfor %}
            </div>
            {% csrf_token %}
          </form>

          <p class="mb-1">
            <a href="forgot-password.html">I forgot my password</a>
          </p>
          <p class="mb-0">
            <a href="register.html" class="text-center"
              >Register a new membership</a
            >
          </p>
        </div>
        <!-- /.login-card-body -->
      </div>
    </div>
    <!-- /.login-box -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
  </body>
</html>

authentication/templates/authentication/register.html
{% extends 'base.html' %}{% load static from static %} {% load crispy_forms_tags %} {% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css'%}">
<script type="text/javascript" src="/admin/jsi18n/"></script>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark"><i class="fas fa-users"></i>&nbsp;{{ title }}</h1>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">{{ title }}</li>
                </ol>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<div class="card card-danger card-outline">
    <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% crispy user_form %}
        </form>
    </div>
</div>
{% endblock %} {% block javascript %}
<script src="{% static 'js/password_score.js' %}"></script>
<script>
    $(document).ready(function() {
        $(':password').pwstrength({
            ui: {
                showVerdictsInsideProgressBar: true
            }
        });
    });
    $(function(){
        $('#div_id_groups').find('.select2').remove();
        $('#div_id_user_permissions').find('.select2').remove();
        $('#id_password').text('********************');
    });
</script>
{% endblock %}