WEAS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home',include('home.urls')),
    path('',include('user.urls')),
]

api/api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/alert/', include('users.urls')),
    path('api/v1/', include('survey.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.authtoken')),
]

authentication/urls.py
from django.urls import path
from .views import *
app_name = 'auth'
urlpatterns = [
    path('user',user_list,name="user_index"),
    path('group',group_index,name="group_index"),
    path('permission',permission_index,name="permission_index"),
    path('user/register',register,name="user_create"),
    path('group/create',group_create,name="group_create"),
    path('user/edit/<id>/',user_update,name="user_update"),
    path('user/delete',user_delete,name="user_delete"),
    path('user/edit/<id>/password/',change_password,name="password_change"),
    path('group/edit/<id>/',group_update,name="group_update"),
]

hack/hack/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import View
from hackathon.views.views import *
from hackathon.views.faq import *
from hackathon.views.location import *
from hackathon.views.user_assessment import *
from hackathon.views.risk_assessment import *
from hackathon.views.user import *
from hackathon.views.personal_contact import *
from hackathon.views.personal_city import *
import hackathon
from hackathon.views.weatherMail import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', getRoutes),
    path('user/', getUsers),
    # path('user/<str:pk>/', getUsers),
    path('user/insert/', insertUser),
    path('user/update/', updateUser),
    path('user/signin/', userSignIn),
    path('location/', getLocations),
    path('location/insert/', insertLocation),
    path('location/update/', updateLocation),
    path('faq/', getFAQs),
    path('faq/insert/', insertFAQ),
    path('faq/update/', updateFAQ),
    path('userassessment/', getUserAssessments),
    path('userassessment/insert/', insertUserAssessment),
    path('userassessment/update/', updateUserAssessment),
    path('riskassessment/', getRiskAssessments),
    path('riskassessment/insert/', insertRiskAssessment),
    path('riskassessment/update/', updateRiskAssessment),
    path('personalcontact/', getPersonalContacts),
    path('personalcontact/insert/', insertPersonalContact),
    path('personalcontact/update/', updatePersonalContact),
    path('personalcity/', getPersonalCitys),
    path('personalcity/insert/', insertPersonalCity),
    path('personalcity/update/', updatePersonalCity),
    path('initiatethreshold/', initiateThreshold),
]

weas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import login_page, register, logout_user, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('register/',register),
    path('login/',login_page,name='login'),
    path('logout/',logout_user,name='logout'),
    path('authentication/',include('authentication.urls',namespace='authentication')),
    path('risk-assesment/',include('risk_assesment.urls',namespace='risk_assesment')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

templates/create.html
{% extends 'base.html' %}} {% load crispy_forms_tags %} {% block content%}
<div class="card card-default">
    <div class="card-header bg-danger">
        <div class="row" style="height:40px;">
            <div class="col-sm-6">
                <h4 class="text-white" style="margin-top: 1%;"><i class="fas fa-user-graduate"></i>&nbsp; {{ title }}</h4>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right bg-danger">
                    <li class="breadcrumb-item text-white"><a href="{% url 'home' %}">Home</a></li>
                    <li class="breadcrumb-item active text-white">{{ title }}</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="card-body">

        <form action="" enctype="multipart/form-data" method="POST">
            {% crispy form %}
        </form>
    </div>
</div>
<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block javascript %}
<script>
    $(function() {
        var table = $('#table').DataTable({
            'responsive': true,
            dom: 'Bfrtip',
            buttons: ['copy', 'csv', 'excel', 'pdf', 'print', 'colvis'],
        });
        table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container()));

        $('.select').select2({
            'theme': "bootstrap4",
            'width': '100%',

        });

        $('.dateinput').datepicker({
            startView: 3,
            autoclose: true
        });
    });
</script>
{% endblock %}

templates/js.html
<script>
    $.each(inputs, function(i, ele) {
        keys.push(ele.name);
    });

    $(document).submit($addForm, function(event) {
        event.preventDefault();
        var $formData = $(this).serialize()

        $.ajax({
            method: "POST",
            url: $url,
            data: $formData,
            headers: {
                "X-CSRFToken": '{{csrf_token}}'
            },
            success: handleFormSuccess,
            error: handleFormError,
        });
    });

    function handleFormSuccess(data, textStatus, jqXHR) {
        $addForm[0].reset();
        $modal_form.modal('hide');
        $(location).attr('href', url)
    }

    function handleFormError(jqXHR, textStatus, errorThrown) {

        $.each(keys, function(i, ele) {
            error = $.parseJSON(jqXHR.responseText)[ele]
            $('#' + ele + '-error').remove();
            if (error != undefined) {
                var $field = $("input[name=" + ele + "]");
                var $label = $("#id_" + ele).text();
                $field.addClass('is-invalid');
                $field.after(
                    '<span id="' + ele + '-error" class="error invalid-feedback">' + error + '</span>');
            } else {
                $('#' + ele + '-error').remove();
                $("input[name=" + ele + "]").removeClass('is-invalid');
            }

        });

    }

    var table = $table.DataTable({
        'responsive': true,
        dom: 'Bfrtip',
        buttons: ['copy', 'csv', 'excel', 'pdf', 'print', 'colvis'],
    });
    table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.table().container()));
    $(document).on('click', '.add-link', function() {
        $addForm.find('input').removeClass('is-invalid');
        $addForm.find('error').html('');
        $modal_form.modal();
    });

    $(document).on('click', '.modal-close', function() {

    });

    $(document).on("hide.bs.modal", $modal_form, function() {
        $modal_form.find('form')[0].reset();
        $addForm.children().removeClass('is-invalid');
    });

    $(document).on('click', '.btn-edit', function() {
        var $slug = $(this).attr('slug');
        $.getJSON($api_url + $slug, function(data) {
            $.each(keys, function(i, ele) {
                if (data[ele] != undefined) {
                    $("input[name=" + ele + "]").val(data[ele]);
                    $modal_form.modal('show');
                }
            });
        });
    });
</script>

templates/sidebar.html
{% load static from static %}
<aside class="main-sidebar sidebar-light-primary elevation-4 ">
  
  <!-- Sidebar Menu -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <span
          class="avatar"
          style="background-image: url('{{ request.user.image.url }}')"
        ></span>
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ request.user }}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul
        class="nav nav-pills nav-sidebar flex-column nav-child-indent nav-legacy"
        data-widget="treeview"
        role="menu"
        data-accordion="false"
      >
        <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
        <li
          class="nav-item has-treeview {% if active_menu == 'authentication' %}menu-open{% endif %}"
        >
          <a
            href="#"
            class="nav-link {% if active_menu == 'authentication' %}active{% endif %}"
          >
            <i class="nav-icon fas fa-user-shield"></i>
            <p>
              Authentication
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a
                href="{% url 'authentication:user_index' %}"
                class="nav-link {% if title == 'User' %}active{% endif %}"
              >
                <i class="far fa-circle nav-li"></i>
                <p>User</p>
              </a>
            </li>
            <li class="nav-item">
              <a
                href="{% url 'authentication:group_index' %}"
                class="nav-link {% if title == 'Group' %}active{% endif %}"
              >
                <i class="far fa-circle nav-li"></i>
                <p>Group</p>
              </a>
            </li>
          </ul>
          <li class="nav-item">
            <a
              href="{% url 'authentication:group_index' %}"
              class="nav-link {% if title == 'Group' %}active{% endif %}"
            >
            <i class="fas fa-house-damage"></i>
              <p>Risk Assesment</p>
            </a>
          </li>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar-menu -->
  <!-- /.sidebar -->
</aside>

templates/test.html
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="{% static 'img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block text-capitalize">{{ request.user }}</a>
        </div>
    </div>

    <!-- Sidebar Menu -->
    <div class="hleft">
        <a class="header-brand" href="index.html"><i class="fa fa-graduation-cap brand-logo"></i></a>
        <div class="dropdown">
            <a href="javascript:void(0)" class="nav-link icon menu_toggle"><i class="fe fe-align-center"></i></a>
            <a href="page-search.html" class="nav-link icon"><i class="fe fe-search" data-toggle="tooltip" data-placement="right" title="" data-original-title="Search..." aria-describedby="tooltip145612"></i></a>
            <a href="app-email.html" class="nav-link icon app_inbox"><i class="fe fe-inbox" data-toggle="tooltip" data-placement="right" title="" data-original-title="Inbox"></i></a>
            <a href="app-filemanager.html" class="nav-link icon app_file xs-hide"><i class="fe fe-folder" data-toggle="tooltip" data-placement="right" title="" data-original-title="File Manager"></i></a>
            <a href="app-social.html" class="nav-link icon xs-hide"><i class="fe fe-share-2" data-toggle="tooltip" data-placement="right" title="" data-original-title="Social Media" aria-describedby="tooltip206475"></i></a>
            <a href="javascript:void(0)" class="nav-link icon theme_btn"><i class="fe fe-feather"></i></a>
            <a href="javascript:void(0)" class="nav-link icon settingbar"><i class="fe fe-settings"></i></a>
        </div>
    </div>
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
   with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{% url 'students:student_index' %}" class="nav-link">
                    <i class="nav-icon fas fa-user-graduate"></i>
                    <p>
                        Student
                    </p>
                </a>
            </li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-copy"></i>
                    <p>
                        Layout Options
                        <i class="fas fa-angle-left right"></i>
                        <span class="badge badge-info right">6</span>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="pages/layout/top-nav.html" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Top Navigation</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="pages/layout/top-nav-sidebar.html" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Top Navigation + Sidebar</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="pages/layout/boxed.html" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Boxed</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="pages/layout/fixed-sidebar.html" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Fixed Sidebar</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="pages/layout/fixed-topnav.html" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Fixed Navbar</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="pages/layout/fixed-footer.html" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Fixed Footer</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="pages/layout/collapsed-sidebar.html" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Collapsed Sidebar</p>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>